apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-config
  namespace: ai-hospital-assistant
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  LOKI_URL: "http://loki:3100"
  PROMETHEUS_SCRAPE_PATH: "/metrics"
