import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const app = readFileSync(new URL("../src/main.tsx", import.meta.url), "utf8");
const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");

assert.match(app, /AI_REVIEW_DISCLAIMER/);
assert.match(app, /ROLE_NAMES/);
assert.match(app, /Email Login/);
assert.match(app, /Mobile OTP/);
assert.match(app, /Hospital Tenant Setup/);
assert.match(app, /Domain mapping/);
assert.match(app, /Role-Based Access/);
assert.match(app, /PERMISSION_NAMES/);
assert.match(app, /Hospital Management/);
assert.match(app, /Departments/);
assert.match(app, /Staff Management/);
assert.match(app, /Doctor schedules/);
assert.match(app, /Patient Management/);
assert.match(app, /Medical history/);
assert.match(app, /Appointment System/);
assert.match(app, /Queue management/);
assert.match(app, /Reception Dashboard/);
assert.match(app, /Walk-ins/);
assert.match(app, /Doctor Dashboard/);
assert.match(app, /Pending documentation/);
assert.match(app, /Nurse Dashboard/);
assert.match(app, /Shift handover/);
assert.match(app, /Laboratory Module/);
assert.match(app, /Sample tracking/);
assert.match(app, /Pharmacy Module/);
assert.match(app, /Interaction warnings/);
assert.match(app, /Billing Module/);
assert.match(app, /GST and discounts/);
assert.match(app, /Insurance Module/);
assert.match(app, /Claim preparation/);
assert.match(app, /Notification System/);
assert.match(app, /Email and SMS/);
assert.match(app, /AI Reception Agent/);
assert.match(app, /Queue estimates/);
assert.match(app, /AI Doctor Agent/);
assert.match(app, /Clinician review/);
assert.match(app, /AI Nurse Agent/);
assert.match(app, /Handover drafts/);
assert.match(app, /AI Patient Assistant/);
assert.match(app, /No medical advice/);
assert.match(app, /AI Voice Follow-Up Agent/);
assert.match(app, /Reviewed scripts/);
assert.match(styles, /grid-template-columns/);

console.log("web setup smoke tests passed");
